eagleye:
 reverse_imu: false

 velocity_scale_factor:                                #Parameters for estimating vehicle speed scale factor
  estimated_number_min: 3200                           #Minimum number of data used for estimation.
  estimated_number_max: 64000                          #Maximum number of data used for estimation.
  estimated_velocity_threshold: 2.78                   #Velocity threshold at which to start estimation. (m/s)
  estimated_coefficient: 0.0125                        #A coefficient for determining the threshold for the number of valid data in the buffer to determine whether to make an estimate.

 yawrate_offset_stop:                                  #Parameters related to estimation of yaw rate offset due to temperature drift and noise of IMU during stoppage
   stop_judgment_velocity_threshold: 0.01              #Speed threshold for judgment at stop. (m/s)
   estimated_number: 200                               #Number of data used for estimation.

 yawrate_offset:                                       #Parameters related to estimation of yaw rate offset due to temperature drift and noise of IMU while driving
   estimated_number_min: 6000                          #Minimum number of data used for estimation.
   estimated_coefficient: 0.005                        #A coefficient for determining the threshold for the number of valid data in the buffer to determine whether to make an estimate.
   estimated_velocity_threshold: 2.78                  #Velocity threshold at which to start estimation. (m/s)
   1st:
     estimated_number_max: 56000                       #Maximum number of data used for estimation.
   2nd:
     estimated_number_max: 100000                      #Maximum number of data used for estimation.

 heading:                                              #Parameters for estimating the azimuth of a car
   estimated_number_min: 2000                          #Minimum number of data used for estimation.
   estimated_number_max: 6000                          #Maximum number of data used for estimation.
   estimated_gnss_coefficient: 0.025
   estimated_heading_coefficient: 0.0125
   outlier_threshold: 0.005305
   estimated_velocity_threshold: 2.78                  #Velocity threshold at which to start estimation. (m/s)
   stop_judgment_velocity_threshold: 0.01              #Speed threshold for judgment at stop. (m/s)
   estimated_yawrate_threshold: 0.008842

 heading_interpolate:
   stop_judgment_velocity_threshold: 0.01              #Speed threshold for judgment at stop. (m/s)

 trajectory:
   stop_judgment_velocity_threshold: 0.01              #Speed threshold for judgment at stop. (m/s)

 position:
   estimated_distance: 2000
   separation_distance: 0.1
   estimated_velocity_threshold: 2.78
   outlier_threshold: 3
   estimated_enu_vel_coefficient : 0.025
   estimated_position_coefficient: 0.005
   ecef_base_pos_x : 0.0                               #The position in the ecef coordinate system to use when converting to the enu coordinate system. If 0, the position entered for the first time when starting the program will be used as a reference.
   ecef_base_pos_y : 0.0
   ecef_base_pos_z : 0.0
