
name: build
on: push

jobs:
  build:
    runs-on:  ubuntu-18.04
    
    container: ros:melodic
    services:
      ros:
        image: ros

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install rtklib_msgs
        run: |
            git clone https://github.com/MapIV/rtklib_ros_bridge.git

      - name: Install catkin
        run: |
            apt-get update -qq && apt-get install -y python-catkin-tools
            source /opt/ros/melodic/setup.bash
            rosdep install --from-paths . --ignore-src -y --rosdistro melodic

      - name: Install ros-melodic-can-msgs
        run: |
            apt-get install ros-melodic-can-msgs

      - name: Install ros-melodic-geodesy
        run: |
            apt-get install ros-melodic-geodesy

      - name: Install GeographicLib
        run: |
            apt-get install -y libgeographic-dev geographiclib-tools geographiclib-doc


      - name: Build
        run: |
            source /opt/ros/melodic/setup.bash
            mkdir -p /tmp/ws/src
            ln -s `pwd` /tmp/ws/src/package
            cd /tmp/ws/src
            catkin_init_workspace
            cd ../
            catkin_make -DCMAKE_BUILD_TYPE=Release -j1
