
name: build
on: push

jobs:
  build:
    runs-on:  ubuntu-18.04
    
    container: ros:melodic
    services:
      ros:
        image: ros

    defaults:
      run:
        shell: bash

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: rosdep update
        run: |
          apt-get update
          rosdep update

      - name: Create Workspace
        run: |
          mkdir -p ~/eagleye/src/
          cp -r `pwd` ~/eagleye/src/
          ls ~/eagleye/src/

      - name: Clone rtklib_msgs
        run: |
          git clone https://github.com/MapIV/rtklib_ros_bridge.git
        working-directory: ~/eagleye/src/

      - name: Build
        run: |
          source /opt/ros/melodic/setup.bash
          rosdep install --from-paths src --ignore-src -r -y
          catkin_make -DCMAKE_BUILD_TYPE=Release -j1
        working-directory: ~/eagleye/